### ISSUE TITLE
Rocket favicon

### ISSUE THREAD

**Issue by stevesong** [life-itself/web3#121] opened 2022-04-13 13:31 UTC
Is the choice of a "rocket" as the favicon for the site intentional?  Some kind of ironic play on the "to the moon" crypto meme?  Perhaps something more neutral but indicative of the multidimensionality of the issue. e.g. https://thumbs.dreamstime.com/z/going-all-directions-4142189.jpg

**Comment by rufuspollock** [comment] 2022-04-14 10:37
@stevesong good point and had this in #70 and just split out to #174 which could either merge to here or vice-versa.

To answer the question: rocket was accidental - just a placeholder.

Be great to have a solution.

**Comment by stevesong** [comment] 2022-04-14 11:47
merge to #124

**Comment by rufuspollock** [comment] 2022-04-14 12:47
FIXED. Duplicate of #124

**Closed by rufuspollock** 2022-04-14 12:47 UTC
Labels: duplicate
